version: '3.1'

services:
  web:
    build: .
    volumes:
      - .:/app
    command: sleep infinity
    ports:
      - "3000:3000"

  db:
    image: postgres:12
    restart: always
    volumes:
      - ./db/db_data:/var/lib/postgresql/data
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: dragons


  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

